on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    name: A job to say hello (greetings)
    steps:
      - name: Hello world action step
        id: hello
        uses: omenking/barsoom@0.0.6
        with:
          name: 'Suman'
      # Use the output from the `hello` step
      - name: Get the Output

        run: echo "The time was ${{ steps.hello.outputs.greeting }}"
